/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;

[BurstCompile]
public struct TerrainChunk
{
    public NativeHashMap<int3, Block> points;
    public NativeReference<bool> isGenerated;
    
    private const int CHUNK_WIDTH = 32;
    
    [BurstCompile]
    public static void Initialize(out TerrainChunk chunk)
    {
        chunk = new TerrainChunk
        {
            points = new(100, Allocator.Persistent),
            isGenerated = false
        };
    }
    
    [BurstCompile]
    public static void Dispose(in TerrainChunk chunk)
    {
        chunk.points.Dispose();
    }
}
