/* File generated by PythonTerrainSourceGenerator */

using System;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

[BurstCompile]
public struct TerrainCluster
{
    private NativeHashMap<int3, TerrainChunk> chunks;
    private NativeHashMap<int3, JobHandle> jobs;
    private int seed;
    
    private const int CHUNK_WIDTH = 32;
    
    [BurstCompile]
    public static void Initialize(int seed, out TerrainCluster cluster)
    {
        cluster = new TerrainCluster
        {
            chunks = new (1000, Allocator.Persistent),
            jobs = new (1000, Allocator.Persistent),
            seed = seed
        };
    }
    
    [BurstCompile]
    public static bool DidStartGeneratingChunk(ref TerrainCluster cluster, int3 chunkPos)
    {
        return cluster.chunks.ContainsKey(chunkPos);
    }
    
    [BurstCompile]
    public static bool DidFinishGeneratingChunk(ref TerrainCluster cluster, int3 chunkPos)
    {
        return cluster.chunks.TryGetValue(chunkPos, out TerrainChunk chunk) && chunk.isGenerated;
    }
    
    [BurstCompile]
    public static TerrainChunk GetChunk(ref TerrainCluster cluster, int3 chunkPos)
    {
        return cluster.chunks[chunkPos];
    }
    
    [BurstCompile]
    public static TerrainChunk SetChunk(ref TerrainCluster cluster, int3 chunkPos, TerrainChunk chunk)
    {
        cluster.chunks[chunkPos] = chunk;
    }
    
    [BurstCompile]
    public static bool GenerateChunk(ref TerrainCluster cluster, int3 chunkPos, out JobHandle handle)
    {
        if (TerrainCluster.DidStartGeneratingChunk(ref cluster, chunkPos))
        {
            handle = new JobHandle {};
            return false;
        }
        
        TerrainChunk.Initialize(out TerrainChunk chunk);
        cluster.chunks[chunkPos] = chunk;
        TerrainJob job = new TerrainJob
        {
            chunk = chunk,
            chunkX = chunkPos.x,
            chunkY = chunkPos.y,
            chunkZ = chunkPos.z,
            seed = cluster.seed
        }
        
        handle = job.Schedule();
        cluster.jobs[chunkPos] = handle;
        return true;
    }
    
    [BurstCompile]
    public static void Dispose(ref TerrainCluster cluster)
    {
        if (cluster.chunks.Count > 0)
        {
            NativeArray<TerrainChunk> chunksToDispose = cluster.chunks.GetValueArray(Allocator.Temp);
            foreach (TerrainChunk chunk in chunksToDispose)
            {
                TerrainChunk.Dispose(chunk);
            }
            chunksToDispose.Dispose();
        }
        cluster.chunks.Dispose();
        cluster.jobs.Dispose();
    }
}
