/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;

[BurstCompile]
public struct TerrainJob : IJob
{
    public TerrainChunk chunk;
    [ReadOnly] public int chunkX;
    [ReadOnly] public int chunkY;
    [ReadOnly] public int chunkZ;
    [ReadOnly] public int seed;
    
    private const int CHUNK_WIDTH = 32;
    private const int BIOME_COMPOSITIONS_CHUNK_RANGE = 0;
    private const int ALTITUDES_CHUNK_RANGE = 0;
    
    [BurstCompile]
    public static void AddBiomeCompositionsChunk(ref TerrainJob job, BiomeCompositionsChunk chunk, in int2 chunkPos)
    {
        job.biomeCompositionsChunks[GetBiomeCompositionsIndex(chunkPos)] = chunk;
    }
    
    [BurstCompile]
    private static int GetBiomeCompositionsIndex(in int2 chunkPos)
    {
        return (chunkPos.x + 0) + ((chunkPos.y + 0) * 1);
    }
    
    [BurstCompile]
    private static void FetchBiomeCompositionsFrom(ref TerrainJob job, ref NativeList<BiomeComposition> points, in int2 offset)
    {
        BiomeCompositionsChunk chunk = job.biomeCompositionsChunks[GetBiomeCompositionsIndex(chunkPos)] = chunk;
        
        foreach (BiomeComposition point in chunk.points)
        {
            int chunkX = job.chunkX + offset.x;
            int chunkY = job.chunkY + offset.y;
            
            BiomeComposition newPoint = point;
            newPoint.localX = point.localX + (chunkX * 32);
            newPoint.localY = point.localY + (chunkY * 32);
            points.Add(newPoint);
        }
    }
    
    [BurstCompile]
    public static void AddAltitudesChunk(ref TerrainJob job, AltitudesChunk chunk, in int2 chunkPos)
    {
        job.altitudesChunks[GetAltitudesIndex(chunkPos)] = chunk;
    }
    
    [BurstCompile]
    private static int GetAltitudesIndex(in int2 chunkPos)
    {
        return (chunkPos.x + 0) + ((chunkPos.y + 0) * 1);
    }
    
    [BurstCompile]
    private static void FetchAltitudesFrom(ref TerrainJob job, ref NativeList<int> points, in int2 offset)
    {
        AltitudesChunk chunk = job.altitudesChunks[GetAltitudesIndex(chunkPos)] = chunk;
        
        foreach (int point in chunk.points)
        {
            int chunkX = job.chunkX + offset.x;
            int chunkY = job.chunkY + offset.y;
            
            int newPoint = point;
            newPoint.localX = point.localX + (chunkX * 32);
            newPoint.localY = point.localY + (chunkY * 32);
            points.Add(newPoint);
        }
    }
    
    [BurstCompile]
    public void Execute()
    {
        if (chunk.isGenerated.Value) return;
        
        NativeList<BiomeComposition> biomeCompositions = new(100, Allocator.TempJob);
        for (int x = -0; x < 0; x++)
        {
            for (int y = -0; y < 0; y++)
            {
                FetchBiomeCompositionsFrom(ref this, ref biomeCompositions, new int2(x, y));
            }
        }
        
        NativeList<int> altitudes = new(100, Allocator.TempJob);
        for (int x = -0; x < 0; x++)
        {
            for (int y = -0; y < 0; y++)
            {
                FetchAltitudesFrom(ref this, ref altitudes, new int2(x, y));
            }
        }
        
        /* Partial routine - injected into job script by source generator */        
        biomeCompositions.Dispose();
        altitudes.Dispose();
        chunk.isGenerated.Value = true;
    }
}
