/* File generated by PythonTerrainSourceGenerator */

using System;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

[BurstCompile]
public struct BiomePointsCluster
{
    private NativeHashMap<int2, BiomePointsChunk> chunks;
    private NativeHashMap<int2, JobHandle> jobs;
    private int seed;
    
    [BurstCompile]
    public static void Initialize(int seed, out BiomePointsCluster cluster)
    {
        cluster = new BiomePointsCluster
        {
            chunks = new (1000, Allocator.Persistent),
            jobs = new (1000, Allocator.Persistent),
            seed = seed
        };
    }
    [BurstCompile]
    public static bool DidStartGeneratingChunk(ref BiomePointsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.ContainsKey(chunkPos);
    }
    
    [BurstCompile]
    public static bool DidFinishGeneratingChunk(ref BiomePointsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.TryGetValue(chunkPos, out BiomePointsChunk chunk) && chunk.isGenerated;
    }
    
    [BurstCompile]
    public static BiomePointsChunk GetChunk(ref BiomePointsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks[chunkPos];
    }
    
    [BurstCompile]
    public static BiomePointsChunk SetChunk(ref BiomePointsCluster cluster, int2 chunkPos, BiomePointsChunk chunk)
    {
        cluster.chunks[chunkPos] = chunk;
    }
    
    [BurstCompile]
    public static bool GenerateChunk(ref BiomePointsCluster cluster, int2 chunkPos, out JobHandle handle)
    {
        if (BiomePointsCluster.DidStartGeneratingChunk(ref cluster, chunkPos))
        {
            handle = new JobHandle {};
            return false;
        }
        
        BiomePointsChunk.Initialize(out BiomePointsChunk chunk);
        cluster.chunks[chunkPos] = chunk;
        BiomePointsJob job = new BiomePointsJob
        {
            chunk = chunk,
            chunkX = chunkPos.x,
            chunkY = chunkPos.y,
            seed = cluster.seed
        };
        
        handle = job.Schedule();
        cluster.jobs[chunkPos] = handle;
        return true;
    }
    
    [BurstCompile]
    public static void Dispose(ref BiomePointsCluster cluster)
    {
        if (cluster.chunks.Count > 0)
        {
            NativeArray<BiomePointsChunk> chunksToDispose = cluster.chunks.GetValueArray(Allocator.Temp);
            foreach (BiomePointsChunk chunk in chunksToDispose)
            {
                BiomePointsChunk.Dispose(chunk);
            }

            chunksToDispose.Dispose();
        }

        cluster.chunks.Dispose();
        cluster.jobs.Dispose();
    }

}

