/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;

[BurstCompile]
public struct BiomePointsJob : IJob
{
    public BiomePointsChunk chunkData;
    [ReadOnly] public int chunkX;
    [ReadOnly] public int chunkY;
    [ReadOnly] public int seed;
    
    [BurstCompile]
    public void Execute()
    {
        if (chunkData.isGenerated) return;
        
