import os

GENERAL_HEADER = "/* File generated by PythonTerrainSourceGenerator */\n\n"
OUTPUT_DIR = 'Output'

class CodeWriter:
    def __init__(self, layer, file_name):
        directory = os.path.join(OUTPUT_DIR, layer['class_prefix'])
        os.makedirs(directory, exist_ok=True)
        self.f = open(os.path.join(directory, file_name), mode='w', encoding='utf-8')
        self.f.write(GENERAL_HEADER)
        self.indent = 0
    
    def write(self, text):
        self.f.write("    " * self.indent)
        self.f.write(text)

    # Add an indent to all future lines
    def shift_right(self):
        self.indent += 1
    
    # Remove an indent from all future lines
    def shift_left(self):
        self.indent -= 1
    
    # Create an opening brace and shift left.
    def open_func(self):
        self.write("{\n")
        self.shift_right()
    
    # Create a closing brace and shift left.
    def close_func(self):
        self.shift_left()
        self.write("}\n\n")
    
    def close(self):
        self.f.close()
