import os

GENERAL_HEADER = "/* File generated by PythonTerrainSourceGenerator */\n\n"
OUTPUT_DIR = 'Output'
ROUTINES_DIR = 'Routines'

class CodeWriter:
    def __init__(self, layer, file_name):
        directory = os.path.join(OUTPUT_DIR, layer['pascal_prefix'])
        os.makedirs(directory, exist_ok=True)
        self.f = open(os.path.join(directory, file_name), mode='w', encoding='utf-8')
        self.f.write(GENERAL_HEADER)
        self.indent = 0
    
    # Add text to the file with proper indentation.
    def put(self, text):
        self.f.write("    " * self.indent)
        self.f.write(text)

    # Add an indent to all future lines
    def shift_right(self):
        self.indent += 1
    
    # Remove an indent from all future lines
    def shift_left(self):
        self.indent -= 1
    
    # Create an opening brace and shift left.
    def open_func(self):
        self.put("{\n")
        self.shift_right()
    
    # Create a closing brace and shift left.
    def close_func(self):
        self.shift_left()
        self.put("}\n")

    # Load all code from a separate file into this file.
    def load_routine(self, routine):
        routine_f = open(os.path.join(ROUTINES_DIR, routine), mode='r', encoding='utf-8')
        line = routine_f.readline()
        while (len(line) > 0):
            self.put(line)
            line = routine_f.readline()
        routine_f.close()
    
    def close(self):
        self.f.close()
