/* File generated by PythonTerrainSourceGenerator */

using System;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

[BurstCompile]
public struct HillPointsCluster
{
    [ReadOnly] public BiomeCompositionsCluster biomeCompositionsCluster;
    private NativeHashMap<int2, HillPointsChunk> chunks;
    private NativeHashMap<int2, JobHandle> jobs;
    private int seed;
    
    private const int CHUNK_WIDTH = 32;
    private const int BIOME_COMPOSITIONS_CHUNK_RANGE = 0;
    
    [BurstCompile]
    public static void Initialize(int seed, out HillPointsCluster cluster)
    {
        cluster = new HillPointsCluster
        {
            chunks = new (1000, Allocator.Persistent),
            jobs = new (1000, Allocator.Persistent),
            seed = seed
        };
    }
    
    [BurstCompile]
    public static bool DidStartGeneratingChunk(ref HillPointsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.ContainsKey(chunkPos);
    }
    
    [BurstCompile]
    public static bool DidFinishGeneratingChunk(ref HillPointsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.TryGetValue(chunkPos, out HillPointsChunk chunk) && chunk.isGenerated;
    }
    
    [BurstCompile]
    public static HillPointsChunk GetChunk(ref HillPointsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks[chunkPos];
    }
    
    [BurstCompile]
    public static HillPointsChunk SetChunk(ref HillPointsCluster cluster, int2 chunkPos, HillPointsChunk chunk)
    {
        cluster.chunks[chunkPos] = chunk;
    }
    
    [BurstCompile]
    public static bool GenerateChunk(ref HillPointsCluster cluster, int2 chunkPos, out JobHandle handle)
    {
        if (HillPointsCluster.DidStartGeneratingChunk(ref cluster, chunkPos))
        {
            handle = new JobHandle {};
            return false;
        }
        
        HillPointsChunk.Initialize(out HillPointsChunk chunk);
        cluster.chunks[chunkPos] = chunk;
        HillPointsJob job = new HillPointsJob
        {
            chunk = chunk,
            biomeCompositionsChunks = new NativeArray<BiomeCompositionsChunk>(1, Allocator.Persistent);
            chunkX = chunkPos.x,
            chunkY = chunkPos.y,
            seed = cluster.seed
        }
        
        NativeList<JobHandle> handles = new NativeList(20, Allocator.Persistent);
        for (int x = -0; x <= 0; x++)
        {
            for (int y = -0; y <= 0; y++)
            {
                int globalX = chunkPos.x + x;
                int globalY = chunkPos.y + y;
                int2 globalPos = new int2(globalX, globalY);
                
                if (BiomeCompositionsCluster.GenerateChunk(ref biomeCompositionsCluster, globalPos, out JobHandle handle))
                {
                    handles.Add(handle);
                }
                job.biomeCompositionsChunks[HillPointsJob.GetBiomeCompositionsIndex(globalPos)] = 
                    BiomeCompositionsCluster.GetChunk(ref biomeCompositionsCluster, globalPos);
            }
        }
        handle = job.Schedule(handles);
        handles.Dispose();
        cluster.jobs[chunkPos] = handle;
        return true;
    }
    
    [BurstCompile]
    public static void Dispose(ref HillPointsCluster cluster)
    {
        if (cluster.chunks.Count > 0)
        {
            NativeArray<BiomeCompositionsChunk> chunksToDispose = cluster.chunks.GetValueArray(Allocator.Temp);
            foreach (BiomeCompositionsChunk chunk in chunksToDispose)
            {
                BiomeCompositionsChunk.Dispose(chunk);
            }
            chunksToDispose.Dispose();
        }
        cluster.chunks.Dispose();
        cluster.jobs.Dispose();
    }
}
