/* File generated by PythonTerrainSourceGenerator */

using System;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

[BurstCompile]
public struct BiomeCompositionsCluster
{
    private NativeHashMap<int2, BiomeCompositionsChunk> chunks;
    private NativeHashMap<int2, JobHandle> jobs;
    private int seed;
    
    private const int CHUNK_WIDTH = 32;
    
    [BurstCompile]
    public static void Initialize(int seed, out BiomeCompositionsCluster cluster)
    {
        cluster = new BiomeCompositionsCluster
        {
            chunks = new (1000, Allocator.Persistent),
            jobs = new (1000, Allocator.Persistent),
            seed = seed
        };
    }
    
    [BurstCompile]
    public static bool DidStartGeneratingChunk(ref BiomeCompositionsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.ContainsKey(chunkPos);
    }
    
    [BurstCompile]
    public static bool DidFinishGeneratingChunk(ref BiomeCompositionsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.TryGetValue(chunkPos, out BiomeCompositionsChunk chunk) && chunk.isGenerated;
    }
    
    [BurstCompile]
    public static BiomeCompositionsChunk GetChunk(ref BiomeCompositionsCluster cluster, int2 chunkPos)
    {
        return cluster.chunks[chunkPos];
    }
    
    [BurstCompile]
    public static BiomeCompositionsChunk SetChunk(ref BiomeCompositionsCluster cluster, int2 chunkPos, BiomeCompositionsChunk chunk)
    {
        cluster.chunks[chunkPos] = chunk;
    }
    
    [BurstCompile]
    public static bool GenerateChunk(ref BiomeCompositionsCluster cluster, int2 chunkPos, out JobHandle handle)
    {
        if (BiomeCompositionsCluster.DidStartGeneratingChunk(ref cluster, chunkPos))
        {
            handle = new JobHandle {};
            return false;
        }
        
        BiomeCompositionsChunk.Initialize(out BiomeCompositionsChunk chunk);
        cluster.chunks[chunkPos] = chunk;
        BiomeCompositionsJob job = new BiomeCompositionsJob
        {
            chunk = chunk,
            chunkX = chunkPos.x,
            chunkY = chunkPos.y,
            seed = cluster.seed
        }
        
        handle = job.Schedule();
        cluster.jobs[chunkPos] = handle;
        return true;
    }
    
    [BurstCompile]
    public static void Dispose(ref BiomeCompositionsCluster cluster)
    {
        if (cluster.chunks.Count > 0)
        {
            NativeArray<BiomeCompositionsChunk> chunksToDispose = cluster.chunks.GetValueArray(Allocator.Temp);
            foreach (BiomeCompositionsChunk chunk in chunksToDispose)
            {
                BiomeCompositionsChunk.Dispose(chunk);
            }
            chunksToDispose.Dispose();
        }
        cluster.chunks.Dispose();
        cluster.jobs.Dispose();
    }
}
