/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;

[BurstCompile]
public struct BiomeCompositionsJob : IJob
{
    public BiomeCompositionsChunk chunk;
    [ReadOnly] public int chunkX;
    [ReadOnly] public int chunkY;
    [ReadOnly] public int seed;
    
    private const int CHUNK_WIDTH = 32;
    private const int BIOME_POINTS_CHUNK_RANGE = 2;
    
    [BurstCompile]
    public static void AddBiomePointsChunk(ref BiomeCompositionsJob job, BiomePointsChunk chunk, in int2 chunkPos)
    {
        job.biomePointsChunks[GetBiomePointsIndex(chunkPos)] = chunk;
    }
    
    [BurstCompile]
    private static int GetBiomePointsIndex(in int2 chunkPos)
    {
        return (chunkPos.x + 2) + ((chunkPos.y + 2) * 5);
    }
    
    [BurstCompile]
    private static void FetchBiomePointsFrom(ref BiomeCompositionsJob job, ref NativeList<Biome> points, in int2 offset)
    {
        BiomePointsChunk chunk = job.biomePointsChunks[GetBiomePointsIndex(chunkPos)] = chunk;
        
        foreach (Biome point in chunk.points)
        {
            int chunkX = job.chunkX + offset.x;
            int chunkY = job.chunkY + offset.y;
            
            Biome newPoint = point;
            newPoint.localX = point.localX + (chunkX * 32);
            newPoint.localY = point.localY + (chunkY * 32);
            points.Add(newPoint);
        }
    }
    
    [BurstCompile]
    public void Execute()
    {
        if (chunk.isGenerated.Value) return;
        
        NativeList<Biome> biomePoints = new(100, Allocator.TempJob);
        for (int x = -2; x < 2; x++)
        {
            for (int y = -2; y < 2; y++)
            {
                FetchBiomePointsFrom(ref this, ref biomePoints, new int2(x, y));
            }
        }
        
        /* Partial routine - injected into job script by source generator */
        
        // Calculate biome compositions for all tiles in the biome chunk
        for (int localX = 0; localX < ClusterChunkSettings.UTILITY_CHUNK_WIDTH; localX++)
        {
            for (int localZ = 0; localZ < ClusterChunkSettings.UTILITY_CHUNK_WIDTH; localZ++)
            {
                BiomeComposition comp = new BiomeComposition
                {
                    biomeCount = 0
                };
                foreach (BiomeLocalPoint biomePoint in biomePoints)
                {
                    float distSquared = math.distancesq(new int2(localX, localZ), new int2(biomePoint.localX, biomePoint.localZ));
                    if (distSquared > ClusterChunkSettings.BIOME_POINT_INFLUENCE_RADIUS * ClusterChunkSettings.BIOME_POINT_INFLUENCE_RADIUS)
                    {
                        continue;
                    }
        
                    // Influence is the reciprocal square root of squared distance,
                    // which is the reciprocal of the distance.
                    float influence = math.rsqrt(distSquared);
        
                    BiomeComposition.AddBiome(ref comp, biomePoint.biome, influence);
                }
                BiomeComposition.Normalize(ref comp);
                BiomeCompositionChunk.SetComposition(ref biomeCompChunk, localX, localZ, comp);
            }
        }
        
        biomePoints.Dispose();
        chunk.isGenerated.Value = true;
    }
}
