/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;

[BurstCompile]
public struct BiomeCompositionsChunk
{
    public NativeHashMap<int2, BiomeComposition> points;
    public NativeReference<bool> isGenerated;
    
    private const int CHUNK_WIDTH = 32;
    
    [BurstCompile]
    public static void Initialize(out BiomeCompositionsChunk chunk)
    {
        chunk = new BiomeCompositionsChunk
        {
            points = new(100, Allocator.Persistent),
            isGenerated = false
        };
    }
    
    [BurstCompile]
    public static void Dispose(in BiomeCompositionsChunk chunk)
    {
        chunk.points.Dispose();
    }
}
