/* File generated by PythonTerrainSourceGenerator */

using System;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

[BurstCompile]
public struct AltitudesCluster
{
    [ReadOnly] public HillPointsCluster hillPointsCluster;
    private NativeHashMap<int2, AltitudesChunk> chunks;
    private NativeHashMap<int2, JobHandle> jobs;
    private int seed;
    
    private const int CHUNK_WIDTH = 32;
    private const int HILL_POINTS_CHUNK_RANGE = 2;
    
    [BurstCompile]
    public static void Initialize(int seed, out AltitudesCluster cluster)
    {
        cluster = new AltitudesCluster
        {
            chunks = new (1000, Allocator.Persistent),
            jobs = new (1000, Allocator.Persistent),
            seed = seed
        };
    }
    
    [BurstCompile]
    public static bool DidStartGeneratingChunk(ref AltitudesCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.ContainsKey(chunkPos);
    }
    
    [BurstCompile]
    public static bool DidFinishGeneratingChunk(ref AltitudesCluster cluster, int2 chunkPos)
    {
        return cluster.chunks.TryGetValue(chunkPos, out AltitudesChunk chunk) && chunk.isGenerated;
    }
    
    [BurstCompile]
    public static AltitudesChunk GetChunk(ref AltitudesCluster cluster, int2 chunkPos)
    {
        return cluster.chunks[chunkPos];
    }
    
    [BurstCompile]
    public static AltitudesChunk SetChunk(ref AltitudesCluster cluster, int2 chunkPos, AltitudesChunk chunk)
    {
        cluster.chunks[chunkPos] = chunk;
    }
    
    [BurstCompile]
    public static bool GenerateChunk(ref AltitudesCluster cluster, int2 chunkPos, out JobHandle handle)
    {
        if (AltitudesCluster.DidStartGeneratingChunk(ref cluster, chunkPos))
        {
            handle = new JobHandle {};
            return false;
        }
        
        AltitudesChunk.Initialize(out AltitudesChunk chunk);
        cluster.chunks[chunkPos] = chunk;
        AltitudesJob job = new AltitudesJob
        {
            chunk = chunk,
            hillPointsChunks = new NativeArray<HillPointsChunk>(25, Allocator.Persistent);
            chunkX = chunkPos.x,
            chunkY = chunkPos.y,
            seed = cluster.seed
        }
        
        NativeList<JobHandle> handles = new NativeList(20, Allocator.Persistent);
        for (int x = -2; x <= 2; x++)
        {
            for (int y = -2; y <= 2; y++)
            {
                int globalX = chunkPos.x + x;
                int globalY = chunkPos.y + y;
                int2 globalPos = new int2(globalX, globalY);
                
                if (HillPointsCluster.GenerateChunk(ref hillPointsCluster, globalPos, out JobHandle handle))
                {
                    handles.Add(handle);
                }
                job.hillPointsChunks[AltitudesJob.GetHillPointsIndex(globalPos)] = 
                    HillPointsCluster.GetChunk(ref hillPointsCluster, globalPos);
            }
        }
        handle = job.Schedule(handles);
        handles.Dispose();
        cluster.jobs[chunkPos] = handle;
        return true;
    }
    
    [BurstCompile]
    public static void Dispose(ref AltitudesCluster cluster)
    {
        if (cluster.chunks.Count > 0)
        {
            NativeArray<HillPointsChunk> chunksToDispose = cluster.chunks.GetValueArray(Allocator.Temp);
            foreach (HillPointsChunk chunk in chunksToDispose)
            {
                HillPointsChunk.Dispose(chunk);
            }
            chunksToDispose.Dispose();
        }
        cluster.chunks.Dispose();
        cluster.jobs.Dispose();
    }
}
