/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;

[BurstCompile]
public struct AltitudesChunk
{
    public NativeHashMap<int2, int> points;
    public NativeReference<bool> isGenerated;
    
    private const int CHUNK_WIDTH = 32;
    
    [BurstCompile]
    public static void Initialize(out AltitudesChunk chunk)
    {
        chunk = new AltitudesChunk
        {
            points = new(100, Allocator.Persistent),
            isGenerated = false
        };
    }
    
    [BurstCompile]
    public static void Dispose(in AltitudesChunk chunk)
    {
        chunk.points.Dispose();
    }
}
