/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;

[BurstCompile]
public struct AltitudesJob : IJob
{
    public AltitudesChunk chunk;
    [ReadOnly] public NativeArray<HillPointsChunk> hillPointsChunks;
    [ReadOnly] public int chunkX;
    [ReadOnly] public int chunkY;
    [ReadOnly] public int seed;
    
    private const int CHUNK_WIDTH = 32;
    private const int HILL_POINTS_CHUNK_RANGE = 2;
    
    [BurstCompile]
    public static void AddHillPointsChunk(ref AltitudesJob job, HillPointsChunk chunk, in int2 chunkPos)
    {
        job.hillPointsChunks[GetHillPointsIndex(chunkPos)] = chunk;
    }
    
    [BurstCompile]
    private static int GetHillPointsIndex(in int2 chunkPos)
    {
        return (chunkPos.x + 2) + ((chunkPos.y + 2) * 5);
    }
    
    [BurstCompile]
    private static void FetchHillPointsFrom(ref AltitudesJob job, ref NativeHashMap<int2, int> localPoints, in int2 offset)
    {
        HillPointsChunk chunk = job.hillPointsChunks[GetHillPointsIndex(chunkPos)] = chunk;
        NativeArray<int2> positions = chunk.points.GetKeyArray(Allocator.Temp);
        
        int chunkX = job.chunkX + offset.x;
        int chunkY = job.chunkY + offset.y;
        
        for (int i = 0; i < positions.Length; i++)
        {
            int2 pos = positions[i];
            int2 adjustedPos = new int2(chunkX * CHUNK_WIDTH, chunkY * CHUNK_WIDTH)
            localPoints.Add(adjustedPos, point);
        }
        positions.Dispose();
    }
    
    [BurstCompile]
    public void Execute()
    {
        if (chunk.isGenerated.Value) return;
        
        NativeHashMap<int2, int> hillPoints = new(100, Allocator.TempJob);
        for (int x = -2; x < 2; x++)
        {
            for (int y = -2; y < 2; y++)
            {
                FetchHillPointsFrom(ref this, ref hillPoints, new int2(x, y));
            }
        }
        
        /* Partial routine - injected into job script by source generator */        
        hillPoints.Dispose();
        chunk.isGenerated.Value = true;
    }
}
