/* File generated by PythonTerrainSourceGenerator */

using Unity.Burst;
using Unity.Collections;

[BurstCompile]
public struct BiomePointsChunk
{
    public NativeHashMap<int2, Biome> points;
    public NativeReference<bool> isGenerated;
    
    private const int CHUNK_WIDTH = 32;
    
    [BurstCompile]
    public static void Initialize(out BiomePointsChunk chunk)
    {
        chunk = new BiomePointsChunk
        {
            points = new(100, Allocator.Persistent),
            isGenerated = false
        };
    }
    
    [BurstCompile]
    public static void Dispose(in BiomePointsChunk chunk)
    {
        chunk.points.Dispose();
    }
}
